<?php
declare(strict_types=1);
session_start(['cookie_httponly'=>true, 'cookie_samesite'=>'Lax', 'cookie_secure'=>!empty($_SERVER['HTTPS'])]);
require_once __DIR__ . '/../src/layout.php';
try { $c = content(); } catch (Throwable $e) { http_response_code(500); echo e($e->getMessage()); exit; }
$path = parse_url($_SERVER['REQUEST_URI'] ?? '/', PHP_URL_PATH) ?: '/';
if ($_SERVER['REQUEST_METHOD'] === 'POST') { handle_post($path); }
render_header($c, title_for($path));
route($path, $c);
render_footer($c);

function title_for(string $path): string { return trim($path, '/') === '' ? '' : ucfirst(explode('/', trim($path, '/'))[0]); }
function route(string $path, array $c): void {
    if ($path === '/') { home($c); return; }
    if ($path === '/einsaetze') { incidents($c); return; }
    if (preg_match('#^/einsaetze/([a-z0-9-]+)$#', $path, $m)) { incident_detail($c, $m[1]); return; }
    if ($path === '/technik') { equipment($c); return; }
    if ($path === '/team') { team($c); return; }
    if ($path === '/ausbildung') { training($c); return; }
    if ($path === '/galerie') { gallery($c); return; }
    if ($path === '/kontakt') { contact($c); return; }
    if ($path === '/impressum') { page_hero('Impressum'); echo '<section class="wrap card"><p><b>TODO:</b> Rechtlich geprüfte Angaben vor Live-Gang ergänzen.</p></section>'; return; }
    if ($path === '/datenschutz') { page_hero('Datenschutzerklärung'); echo '<section class="wrap card"><p><b>TODO:</b> Datenschutzerklärung vor Live-Gang rechtlich prüfen und an Hosting, Formulare, Cookies und Medien anpassen.</p></section>'; return; }
    if ($path === '/admin') { admin($c); return; }
    http_response_code(404); page_hero('Nicht gefunden'); echo '<section class="wrap card"><p>Diese Seite existiert nicht.</p></section>';
}
function home(array $c): void { $primary = $c['equipment'][0]; ?><section class="hero"><div><div class="kicker"><?= e($c['pages']['heroKicker']) ?></div><h1><?= e($c['pages']['heroHeadline']) ?></h1><p><?= e($c['pages']['heroSubline']) ?></p><p><a class="btn red" href="/technik">Mehr erfahren</a> <a class="btn" href="/einsaetze">Aktuelle Einsätze</a></p></div></section><section class="wrap"><h2 class="section-title">Unsere Einsatzbereiche</h2><div class="grid cards4"><?php foreach ($c['areas'] as $a): ?><article class="card area"><div class="redtext" style="font-size:42px">◆</div><div><h3><?= e($a['title']) ?></h3><p><?= e($a['text']) ?></p></div></article><?php endforeach; ?></div></section><section class="wrap grid cols3"><div class="card"><h2 class="section-title">Aktuelle Einsätze</h2><?php foreach ($c['incidents'] as $i): ?><a class="incident" href="/einsaetze/<?= e($i['id']) ?>"><?php img_tag($i['image'],'',''); ?><div><span class="badge">EINSATZ</span><small style="float:right"><?= e(format_date($i['date'])) ?></small><b style="display:block"><?= e($i['title']) ?></b><span><?= e($i['place']) ?></span><p><?= e($i['description']) ?></p></div></a><?php endforeach; ?><a class="redtext" href="/einsaetze">Alle Einsätze ansehen →</a></div><div class="card"><h2 class="section-title">Unser Team</h2><div class="grid teamgrid"><?php foreach ($c['team'] as $m): ?><div><?php img_tag($m['image'],'avatar',$m['name']); ?><b><?= e($m['name']) ?></b><p><?= e($m['role']) ?><br><?= e($m['qualification']) ?></p></div><?php endforeach; ?></div><a class="redtext" href="/team">Mehr über unser Team →</a></div><div class="card"><h2 class="section-title">Unsere Technik</h2><?php img_tag($primary['image'],'equip-img',$primary['name']); ?><h3><?= e($primary['name']) ?></h3><ul class="features"><?php foreach ($primary['features'] as $f): ?><li><?= e($f) ?></li><?php endforeach; ?></ul><a class="redtext" href="/technik">Gesamte Ausrüstung ansehen →</a></div></section><section class="wrap grid mapcta"><div class="mapbox"><h2 class="section-title">Einsatzgebiet Biebertal</h2><div class="outline-map">Krumbach · Frankenbach · Rodheim-Bieber · Fellingshausen · Vetzberg</div></div><div class="cta"><h2><?= e($c['pages']['ctaTitle']) ?></h2><p><?= e($c['pages']['ctaText']) ?></p><h3>Komm in unser Team!</h3><a class="btn" href="/kontakt">Jetzt mitmachen</a></div></section><?php }
function incidents(array $c): void { page_hero('Einsätze','Filterbare Einsatzliste.'); echo '<section class="wrap list">'; foreach ($c['incidents'] as $i) { echo '<article class="card incident">'; img_tag($i['image'],'',''); echo '<div><span class="badge">'.e($i['category']).'</span><h2><a href="/einsaetze/'.e($i['id']).'">'.e($i['title']).'</a></h2><p><b>'.e(format_date($i['date'])).'</b> · '.e($i['place']).' · '.e($i['status']).'</p><p>'.e($i['description']).'</p></div></article>'; } echo '</section>'; }
function incident_detail(array $c, string $id): void { foreach ($c['incidents'] as $i) if ($i['id']===$id) { page_hero($i['title'], format_date($i['date']).' · '.$i['place']); echo '<section class="wrap card">'; img_tag($i['image'],'equip-img',''); echo '<p><span class="badge">'.e($i['category']).'</span> Status: '.e($i['status']).' · Dauer: '.e($i['duration'] ?? '').'</p><p>'.e($i['description']).'</p></section>'; return; } http_response_code(404); page_hero('Einsatz nicht gefunden'); }
function equipment(array $c): void { page_hero('Technik','Drohnen, Sensorik und Zubehör der Fachgruppe.'); echo '<section class="wrap grid cards4">'; foreach($c['equipment'] as $e){ echo '<article class="card">'; img_tag($e['image'],'equip-img',$e['name']); echo '<h2>'.e($e['name']).'</h2><p>'.e($e['description']).'</p><ul class="features">'; foreach($e['features'] as $f) echo '<li>'.e($f).'</li>'; echo '</ul></article>'; } echo '</section>'; }
function team(array $c): void { page_hero('Team','Platzhalterdaten – Veröffentlichung nur mit Einwilligung.'); usort($c['team'], fn($a,$b)=>($a['order']??0)<=>($b['order']??0)); echo '<section class="wrap grid cards4">'; foreach($c['team'] as $m){ echo '<article class="card" style="text-align:center">'; img_tag($m['image'],'avatar',$m['name']); echo '<h2>'.e($m['name']).'</h2><p>'.e($m['role']).'<br>'.e($m['qualification']).'</p></article>'; } echo '</section>'; }
function training(array $c): void { page_hero('Ausbildung'); echo '<section class="wrap card"><p>'.e($c['pages']['training']).'</p><ul class="features"><li>Luftrecht und Datenschutz</li><li>Flugpraxis und Notverfahren</li><li>Wärmebildauswertung</li><li>Einsatzdokumentation</li></ul></section>'; }
function gallery(array $c): void { page_hero('Galerie'); echo '<section class="wrap grid cards4 gallery">'; foreach($c['gallery'] as $g){ echo '<article class="card">'; img_tag($g['url'],'',$g['title']); echo '<h2>'.e($g['title']).'</h2><p>'.e($g['category']).'</p></article>'; } echo '</section>'; }
function contact(array $c): void { page_hero('Kontakt',$c['pages']['contactIntro']); echo '<section class="wrap grid mapcta"><form class="card"><input placeholder="Name"><input placeholder="E-Mail"><textarea placeholder="Nachricht"></textarea><button class="btn red" type="button">Absenden (Demo)</button></form><div class="card"><h2>Kontaktdaten</h2><p>'.e($c['settings']['address']).'</p><p>'.e($c['settings']['email']).'</p><p>'.e($c['settings']['phone']).'</p><div class="mapbox">Karte / Anfahrt (TODO)</div></div></section>'; }
function admin(array $c): void { $user=current_user(); echo '<section class="admin">'; if(!$user){ echo '<div class="card" style="max-width:480px;margin:60px auto"><h1>Admin-Login</h1><p>Initial: admin@feuerwehr-biebertal.local / Drohne112! – beim Live-Gang Hash per ENV setzen.</p>'.(isset($_GET['error'])?'<p class="redtext">Login fehlgeschlagen.</p>':'').'<form method="post"><input type="hidden" name="action" value="login"><input type="hidden" name="csrf" value="'.e(csrf_token()).'"><input name="email" type="email" placeholder="E-Mail" required><input name="password" type="password" placeholder="Passwort" required><button class="btn red">Einloggen</button></form></div></section>'; return; } echo '<div class="adminnav"><a href="#incidents">Einsätze</a><a href="#json">Alle Inhalte</a><form method="post"><input type="hidden" name="action" value="logout"><input type="hidden" name="csrf" value="'.e(csrf_token()).'"><button>Logout</button></form></div><h1>CMS Backend</h1><p>Angemeldet als '.e($user['email']).' ('.e($user['role']).'). Inhalte werden direkt in <code>data/site.json</code> gespeichert.</p>'.(isset($_GET['saved'])?'<p class="redtext">Gespeichert.</p>':'').'<div id="incidents" class="card"><h2>Einsatz anlegen</h2><form method="post" class="grid formgrid"><input type="hidden" name="action" value="add_incident"><input type="hidden" name="csrf" value="'.e(csrf_token()).'"><input name="title" placeholder="Titel" required><input name="date" type="date" required><input name="place" placeholder="Ort" required><select name="category"><option>Personensuche</option><option>Lageerkundung</option><option>Wärmebild</option><option>Dokumentation</option></select><input name="duration" placeholder="Dauer"><input name="image" placeholder="Bild-URL"><textarea name="description" placeholder="Beschreibung" style="grid-column:1/-1" required></textarea><button class="btn red">Speichern</button></form></div><div id="json" class="card" style="margin-top:24px"><h2>Redaktionelle Inhalte bearbeiten</h2><form method="post"><input type="hidden" name="action" value="save_json"><input type="hidden" name="csrf" value="'.e(csrf_token()).'"><textarea name="json">'.e(json_encode($c, JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)).'</textarea><button class="btn red">Alle Inhalte speichern</button></form></div></section>'; }
function handle_post(string $path): void { try { verify_csrf(); $action=$_POST['action']??''; if($action==='login'){ $u=verify_login((string)($_POST['email']??''),(string)($_POST['password']??'')); if(!$u) redirect_to('/admin?error=1'); session_regenerate_id(true); $_SESSION['user']=$u; redirect_to('/admin'); } if($action==='logout'){ $_SESSION=[]; session_destroy(); redirect_to('/admin'); } if(!current_user()) redirect_to('/admin?error=auth'); if($action==='save_json'){ $data=json_decode((string)($_POST['json']??''), true, 512, JSON_THROW_ON_ERROR); save_content($data); redirect_to('/admin?saved=1'); } if($action==='add_incident'){ $c=content(); $title=trim((string)($_POST['title']??'')); if($title==='') throw new RuntimeException('Titel fehlt.'); $c['incidents'][]=['id'=>slugify($title),'title'=>$title,'date'=>(string)($_POST['date']??date('Y-m-d')),'place'=>(string)($_POST['place']??''),'category'=>(string)($_POST['category']??'Lageerkundung'),'status'=>'abgeschlossen','duration'=>(string)($_POST['duration']??''),'image'=>(string)($_POST['image']?:'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80'),'description'=>(string)($_POST['description']??'')]; save_content($c); redirect_to('/admin?saved=1'); } } catch(Throwable $e){ redirect_to('/admin?error='.rawurlencode($e->getMessage())); } }
